import { type Weapon, WeaponType } from "../types";

export const daggers: Weapon[] = [
    {
        name: "Dagger",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/dagger.webp",
        stats: {
            strength: 5,
            dexterity: 9,
            intelligence: 0,
            faith: 0,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Dagger",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Dagger",
        dlcExclusive: false,
    },
    {
        name: "Parrying Dagger",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/parrying_dagger.webp",
        stats: {
            strength: 5,
            dexterity: 14,
            intelligence: 0,
            faith: 0,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Parrying_Dagger",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Parrying+Dagger",
        dlcExclusive: false,
    },
    {
        name: "Miséricorde",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/miséricorde.webp",
        stats: {
            strength: 7,
            dexterity: 12,
            intelligence: 0,
            faith: 0,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Miséricorde",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Miséricorde",
        dlcExclusive: false,
    },
    {
        name: "Great Knife",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/great_knife.webp",
        stats: {
            strength: 6,
            dexterity: 12,
            intelligence: 0,
            faith: 0,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Great_Knife",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Great+Knife",
        dlcExclusive: false,
    },
    {
        name: "Bloodstained Dagger",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/bloodstained_dagger.webp",
        stats: {
            strength: 9,
            dexterity: 12,
            intelligence: 0,
            faith: 0,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Bloodstained_Dagger",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Bloodstained+Dagger",
        dlcExclusive: false,
    },
    {
        name: "Erdsteel Dagger",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/erdsteel_dagger.webp",
        stats: {
            strength: 7,
            dexterity: 12,
            intelligence: 0,
            faith: 14,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Erdsteel_Dagger",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Erdsteel+Dagger",
        dlcExclusive: false,
    },
    {
        name: "Fire Knight's Shortsword",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/fire_knight_shortsword.webp",
        stats: {
            strength: 8,
            dexterity: 13,
            intelligence: 0,
            faith: 12,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Fire_Knight%27s_Shortsword",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Fire+Knight%27s+Shortsword",
        dlcExclusive: true,
    },
    {
        name: "Wakizashi",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/wakizashi.webp",
        stats: {
            strength: 9,
            dexterity: 13,
            intelligence: 0,
            faith: 0,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Wakizashi",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Wakizashi",
        dlcExclusive: false,
    },
    {
        name: "Main-Gauche",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/main_gauche.webp",
        stats: {
            strength: 7,
            dexterity: 15,
            intelligence: 0,
            faith: 0,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Main-gauche",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Main-gauche",
        dlcExclusive: true,
    },
    {
        name: "Celebrant's Sickle",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/celebrant_sickle.webp",
        stats: {
            strength: 6,
            dexterity: 11,
            intelligence: 0,
            faith: 0,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Celebrant%27s_Sickle",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Celebrant%27s+Sickle",
        dlcExclusive: false,
    },
    {
        name: "Ivory Sickle",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/ivory_sickle.webp",
        stats: {
            strength: 6,
            dexterity: 11,
            intelligence: 13,
            faith: 0,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Ivory_Sickle",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Ivory+Sickle",
        dlcExclusive: false,
    },
    {
        name: "Crystal Knife",
        type: WeaponType.Dagger,
        imgPath: "weapons/daggers/crystal_knife.webp",
        stats: {
            strength: 8,
            dexterity: 12,
            intelligence: 9,
            faith: 0,
            arcane: 0,
        },
        wikiGGLink: "https://eldenring.wiki.gg/wiki/Crystal_Knife",
        wikiFextralifeLink: "https://eldenring.wiki.fextralife.com/Crystal+Knife",
        dlcExclusive: false,
    },
    
];